version: '3'
services:
    install:
        image: node
        volumes:
            - ".:/content"
        command: ['npm', 'i', '--prefix', '/content']
    serve:
        image: node
        volumes:
            - ".:/content"
        ports:
            - 8080:8080
        command: ['npm', 'run', 'dev', '--prefix', '/content']